#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrginxDataService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OriginXDB")]
	public partial class OriginXLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public OriginXLinqDataContext() : 
				base(global::OrginxDataService.Properties.Settings.Default.OriginXDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OriginXLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OriginXLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OriginXLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OriginXLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addCustomer")]
		public int addCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phoneno1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phoneno2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string clientlogo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string additionalinfo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, address, type, phoneno1, phoneno2, clientlogo, additionalinfo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addWorldOffice")]
		public int addWorldOffice([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string officename, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string officecountry, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string officeadmin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string officedesc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), officename, officecountry, officeadmin, officedesc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addCountryBranch")]
		public int addCountryBranch([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string coutrybranchcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string branchcity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string branchadmin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string branchdesc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), coutrybranchcode, branchcity, branchadmin, branchdesc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.newemployees")]
		public int newemployees(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nic, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string position, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> basicsalary, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> bonus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userimage, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> hiredate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string department, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> birthday, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sex, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phoneno1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phoneno2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string password, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_level)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, nic, mobile, address, position, basicsalary, bonus, userimage, hiredate, department, birthday, sex, phoneno1, phoneno2, username, password, user_level);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.adddelivery")]
		public int adddelivery([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string deliveryid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sendclientid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> reciveclientid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> startdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> sentdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> enddate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> countrybranchid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> worldbranchid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> salespersonid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> deliverypersonid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deliveryid, sendclientid, reciveclientid, startdate, sentdate, enddate, countrybranchid, worldbranchid, salespersonid, deliverypersonid);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
