<?xml version="1.0" encoding="utf-8"?><Database Name="OriginXDB" Class="OriginXLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=RANGANATH;Initial Catalog=OriginXDB;Integrated Security=True" SettingsObjectName="OrginxDataService.Properties.Settings" SettingsPropertyName="OriginXDBConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.addCustomer" Method="addCustomer">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="type" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="phoneno1" Type="System.Int32" DbType="Int" />
    <Parameter Name="phoneno2" Type="System.Int32" DbType="Int" />
    <Parameter Name="clientlogo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="additionalinfo" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addWorldOffice" Method="addWorldOffice">
    <Parameter Name="officename" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="officecountry" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="officeadmin" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="officedesc" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addCountryBranch" Method="addCountryBranch">
    <Parameter Name="coutrybranchcode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="branchcity" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="branchadmin" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="branchdesc" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.newemployees" Method="newemployees">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="nic" Type="System.Int32" DbType="Int" />
    <Parameter Name="mobile" Type="System.Int32" DbType="Int" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="position" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="basicsalary" Type="System.Int32" DbType="Int" />
    <Parameter Name="bonus" Type="System.Int32" DbType="Int" />
    <Parameter Name="userimage" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="hiredate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="department" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="birthday" Type="System.DateTime" DbType="Date" />
    <Parameter Name="sex" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="phoneno1" Type="System.Int32" DbType="Int" />
    <Parameter Name="phoneno2" Type="System.Int32" DbType="Int" />
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="user_level" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.adddelivery" Method="adddelivery">
    <Parameter Name="deliveryid" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="sendclientid" Type="System.Int32" DbType="Int" />
    <Parameter Name="reciveclientid" Type="System.Int32" DbType="Int" />
    <Parameter Name="startdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="sentdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="enddate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="countrybranchid" Type="System.Int32" DbType="Int" />
    <Parameter Name="worldbranchid" Type="System.Int32" DbType="Int" />
    <Parameter Name="salespersonid" Type="System.Int32" DbType="Int" />
    <Parameter Name="deliverypersonid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>